---
name: Setup terraform

description: Setup Terraform

inputs:
  working-directory:
    description: Terraform CLI 実行時のパス
    required: true

runs:
  using: composite
  steps:
    - name: Get current Terraform version
      run: |
        echo "TERRAFORM_VERSION=$(cat .terraform-version)" >> $GITHUB_ENV
        echo '--------------------------'
        echo $(cat .terraform-version)

      shell: bash

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: env.TERRAFORM_VERSION

    - name: Terraform Format
      run: terraform fmt -check -recursive -diff
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Terraform Init
      run: terraform init -upgrade
      working-directory: ${{ inputs.working-directory }}
      shell: bash
