---
name: Slack Notification (failure)

description: 処理が失敗したときに Slack の指定のチャンネルに通知します。

inputs:
  AWS_ENV_NAME:
    description: 環境名
    required: true
  AWS_ACCOUNT_ID:
    description: AWS アカウント ID
    required: true
  MESSAGE:
    description: 通知するメッセージ
    required: true
  SLACK_WEBHOOK:
    description: Slack Webhook URL
    required: true

runs:
  using: composite
  steps:
    - name: Slack Notification (failure)
      continue-on-error: true
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: "#ntf_pj_musubi_gh_infra"
        SLACK_COLOR: danger
        SLACK_TITLE: "${{ inputs.AWS_ENV_NAME }}(${{ inputs.AWS_ACCOUNT_ID }}): ${{ inputs.MESSAGE }}"
        SLACK_MESSAGE: "<!U0RFFAK9U> 確認してください"
        SLACK_LINK_NAMES: "true"
        SLACK_USERNAME: MusubiCIBot
        SLACK_ICON_EMOJI: ":x:"
        SLACK_WEBHOOK: ${{ inputs.SLACK_WEBHOOK }}
